name: Update ECS Infra

on:
  push:
    branches:
      - UPDATE_BRANCH_NAME_HERE
    paths:
      - "configs/**"
      - "lib/**"
      - "test/**"
      - "utils/**"
      - "ecs-cluster.yaml"
      - "tsconfig.json"
  pull_request:
    branches:
      - UPDATE_BRANCH_NAME_HERE
    paths:
      - "configs/**"
      - "lib/**"
      - "test/**"
      - "utils/**"
      - "ecs-cluster.yaml"
      - "tsconfig.json"
  workflow_dispatch:      

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    environment: UPDATE_ENVIRONMENT_NAME_HERE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm i
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Bootstrap
        run: cdk bootstrap

      - name: CDK Synth
        run: cdk synth

      - name: CDK Diff
        run: cdk diff

      - name: CDK Deploy
        run: cdk deploy --all --require-approval never

permissions:
  id-token: write
  contents: read
